app_port: 8223
container_port: 8000
domain: "v1.api.camwego.com"
server_name: "localhost:{{ app_port }}"
reverse_proxy_file: "templates/camwego.nginx.j2"
sites_available_dir: "/etc/nginx/sites-available"
sites_enabled_dir: "/etc/nginx/sites-enabled"
nginx_max_body_size: 8M

